<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartinaProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int IdCde { get; set; }
        public int IdUtilisateur { get; set; }
        public System.DateTime DateCommande { get; set; }
        public string Panier { get; set; }
        public double PrixTotal { get; set; }
        public string Statut { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartinaProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int IdCde { get; set; }
        public int IdUtilisateur { get; set; }
        public System.DateTime DateCommande { get; set; }
        public string Panier { get; set; }
        public double PrixTotal { get; set; }
        public string Statut { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
>>>>>>> 70b3d106b9b31c8f2087d29f05253eea7d38fd06
